[pfsense-log-processor]

    # keep track of processed windows
    [pfsense-log-processor.mongo-client]
        host = 'mongo-server'
        port = 27017
        database = 'firewall-processor'
        collection = 'state'
        target_db = 'fluent'
        target_collection = 'firewall-raw'
        target_key = 'time'
        start_time = '2017-02-01T00:00:00.0'
        window_secs = 60

    # forward processed firewall logs
    [pfsense-log-processor.fluentd-client]
        host = 'fluent-capture'
        port = 42001

