[firewall-log-processor]

    # keep track of processed windows
    [firewall-log-processor.mongoclient]
        host = 'mongo-server'
        port = 27017
        db = 'firewall-processor'
        collection = 'state'
        target_db = 'fluent'
        target_collection = 'firewall-raw'
        target_key = 'time'
        start = '1970-03-01 00:00:00'
        window_secs = 60


    # forward processed firewall logs
    [firewall-log-processor.fluentdclient]
        host = 'fluent-capture'
        port = 42001

